<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYxtkzga\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYxtkzga/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerYxtkzga.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerYxtkzga\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerYxtkzga\appAppKernelProdContainer([
    'container.build_hash' => 'Yxtkzga',
    'container.build_id' => '32a9a4fb',
    'container.build_time' => 1738770341,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYxtkzga');
