<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'demo_grid.grid.factory.products' shared service.

$a = ($this->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? $this->getHookDispatcherService());

return $this->services['demo_grid.grid.factory.products'] = new \PrestaShop\PrestaShop\Core\Grid\GridFactory(($this->services['demo_grid.grid.definition.factory.products'] ?? $this->load('getDemoGrid_Grid_Definition_Factory_ProductsService.php')), new \PrestaShop\PrestaShop\Core\Grid\Data\Factory\DoctrineGridDataFactory(($this->services['demo_grid.grid.query_builder.product'] ?? $this->load('getDemoGrid_Grid_QueryBuilder_ProductService.php')), $a, ($this->services['prestashop.core.grid.query.doctrine_query_parser'] ?? ($this->services['prestashop.core.grid.query.doctrine_query_parser'] = new \PrestaShop\PrestaShop\Core\Grid\Query\DoctrineQueryParser())), 'product'), ($this->services['prestashop.core.grid.filter.form_factory'] ?? $this->load('getPrestashop_Core_Grid_Filter_FormFactoryService.php')), $a);
