<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.module.mymodule.form.handler' shared service.

return $this->services['prestashop.module.mymodule.form.handler'] = new \PrestaShop\PrestaShop\Core\Form\Handler(($this->services['form.factory'] ?? $this->load('getForm_FactoryService.php')), ($this->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? $this->getHookDispatcherService()), ($this->services['prestashop.module.mymodule.form.data_provider'] ?? $this->load('getPrestashop_Module_Mymodule_Form_DataProviderService.php')), 'PrestaShop\\Module\\MyModule\\Form\\MyModuleConfigurationFormType', 'MyModuleConfiguration');
